FROM golang:1.24 AS builder
RUN update-ca-certificates
WORKDIR /app
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -o netmon-cli ./cmd/cli/main.go

FROM bitnami/minideb:stretch
WORKDIR /app
COPY --from=builder /app/netmon-cli .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT [ "./netmon-cli" ]
