apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmon-deployment
  labels:
    app: netmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmon
  template:
    metadata:
      labels:
        app: netmon      
    spec:
      containers:
      - name: netmon
        image: ghcr.io/mantzas/netmon:0.4.1
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
        - name: SPEED_SERVER_IDS
          value: "5188"
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netmon-service
  annotations:
        k8s.grafana.com/metrics.path:	"/metrics"
        k8s.grafana.com/metrics.portNumber: "80"
        k8s.grafana.com/scrape: "true"
spec:
  selector:
    app: netmon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-speed
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netmon-cronjob-speed
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ["curl"]
            args: ["netmon-service.default.svc.cluster.local:80/api/v1/speed"]
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-ping
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netmon-cronjob-ping
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ["curl"]
            args: ["netmon-service.default.svc.cluster.local:80/api/v1/ping"]
          restartPolicy: OnFailure          
