apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmon-deployment
  labels:
    app: netmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmon
  template:
    metadata:
      labels:
        app: netmon      
    spec:
      containers:      
      - name: netmon
        image: ghcr.io/mantzas/netmon:latest
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PORT
          value: "80"
        - name: SPEED_SERVER_IDS
          value: "5188"
---
apiVersion: v1
kind: Service
metadata:
  name: netmon-service
  annotations:
        k8s.grafana.com/metrics.path:	"/metrics"
        k8s.grafana.com/metrics.portNumber: "80"
        k8s.grafana.com/scrape: "true"
spec:
  selector:
    app: netmon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer