GET http://localhost:8092/api/v1/ping/5188

###

GET http://localhost:8092/api/v1/speed/5188

###

GET http://localhost:8092/health

###110

GET http://localhost:8092/ready

###110

GET http://localhost:8092/metrics
	
	