apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-speed
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: netmon-cronjob-speed
              image: curlimages/curl:8.5.0
              imagePullPolicy: IfNotPresent
              command: ["curl"]
              args: ["netmon-service.netmon.svc.cluster.local:80/api/v1/speed"]
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-ping
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: netmon-cronjob-ping
              image: curlimages/curl:8.5.0
              imagePullPolicy: IfNotPresent
              command: ["curl"]
              args: ["netmon-service.netmon.svc.cluster.local:80/api/v1/ping"]
          restartPolicy: OnFailure
