
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-speed
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netmon-cronjob-speed
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ["curl"]
            args: ["netmon-service.default.svc.cluster.local:80/api/v1/speed"]
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netmon-cronjob-ping
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: netmon-cronjob-ping
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ["curl"]
            args: ["netmon-service.default.svc.cluster.local:80/api/v1/ping"]
          restartPolicy: OnFailure          
