apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmon-deployment
  labels:
    app: netmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmon
  template:
    metadata:
      labels:
        app: netmon
    spec:
      containers:
      - name: netmon
        image: ghcr.io/mantzas/netmon:latest
        ports:
        - containerPort: 80
        env:
        - name: NETMON_HTTP_PORT
          value: "80"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy.observability.svc.cluster.local:4317"
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netmon-service
  annotations:
        k8s.grafana.com/metrics.path:	"/metrics"
        k8s.grafana.com/metrics.portNumber: "80"
        k8s.grafana.com/scrape: "true"
        profiles.grafana.com/memory.port: "80"
        profiles.grafana.com/memory.scrape: "true"
        profiles.grafana.com/cpu.scrape: "true"
        profiles.grafana.com/cpu.port: "80"
        profiles.grafana.com/goroutine.scrape: "true"
        profiles.grafana.com/goroutine.port: "80"
        profiles.grafana.com/heap.scrape: "true"
        profiles.grafana.com/heap.port: "80"
        profiles.grafana.com/block.scrape: "true"
        profiles.grafana.com/block.port: "80"
        profiles.grafana.com/mutex.scrape: "true"
        profiles.grafana.com/mutex.port: "80"
        profiles.grafana.com/allocs.scrape: "true"
        profiles.grafana.com/allocs.port: "80"
        profiles.grafana.com/threads.scrape: "true"
        profiles.grafana.com/threads.port: "80"
        profiles.grafana.com/inflight.scrape: "true"
        profiles.grafana.com/inflight.port: "80"
        profiles.grafana.com/trace.scrape: "true"
        profiles.grafana.com/trace.port: "80"
spec:
  selector:
    app: netmon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
