name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
        
      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
