name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Linting Dockerfile for server
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.server

      - name: Linting Dockerfile for cli
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.cli

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.30.0'
        id: install

      - name: Set up kubectl context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.LOCALK8S_KUBECONFIG }}          
        id: setcontext

      - name: Linting Kubernetes manifests
        uses: azure/k8s-lint@v1
        with:
          lintType: dryrun
          manifests: |
            k8s/deployment_service.yaml
            k8s/cronjob_ping.yaml
            k8s/cronjob_speed.yaml

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Linting Go
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest