name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Linting Dockerfile for server
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.server

      - name: Linting Dockerfile for cli
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.cli

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Linting Go
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest