name: Release
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_SRV: ${{ github.repository }}
  IMAGE_NAME_CLI: "${{ github.repository }}-cli"

jobs:
  publish:
    name: Release netmon in local k8s
    runs-on: [self-hosted]
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Get release version
        # Expect release tags to be in semver format with a 'v' prefix.
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.server
          platforms: linux/amd64
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SRV }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SRV }}:${{ env.RELEASE_VERSION }}"
          build-args: GH_TOKEN=${{ secrets.MANTZAS_GH_TOKEN }}

      - name: Build and push cli image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cli
          platforms: linux/amd64
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLI }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLI }}:${{ env.RELEASE_VERSION }}"
          build-args: GH_TOKEN=${{ secrets.MANTZAS_GH_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        id: install

      - name: Set up kubectl context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.LOCALK8S_KUBECONFIG }}          
        id: setcontext

      - name: Deploy service
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment_service.yaml            
          images: |
            ghcr.io/mantzas/netmon:${{ env.RELEASE_VERSION }}
          imagepullsecrets: |
            ${{ secrets.MANTZAS_GH_TOKEN }}
          namespace: netmon

      - name: Deploy cronjobs
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/cronjobs.yaml
          images: |
            ghcr.io/mantzas/netmon-cli:${{ env.RELEASE_VERSION }}
          namespace: netmon


